### PR TITLE
Verify method described in #99.

### PR DESCRIPTION
**Pull request by jMyles**

### CODE REVIEW

**Comment by jMyles** [comment]
`_internal`?  I definitely don't think that this belongs there.  This is supposed to be a higher-level public function to replace the three-line idiom that we currently have for verification.  I thought we were conspiring around `utils`?  Is that what you meant?

**Comment by tuxxy** [comment]
Until we figure that out more concretely, I'm more comfortable placing it in `_internal.py`. 

If we're going to add a `utils` file, let's talk about what all should be added to it and put it all in one PR.

**Comment by jMyles** [comment]
Well, there's no way this belongs in `_internal`.  If you want to go that direction, it makes more sense to shift `ecdsa_verify` and `ecdsa_load_sig` to `_internal` and put this in `api`.

**Comment by tuxxy** [comment]
I think of `_internal.py` as a staging area for the crypto API. Whether that be some addition to `api` or something that we want to add but don't have a place for yet, see the current function in there.

**Comment by jMyles** [comment]
Subsumed by #101

**Pull request closed without merging**
